Add permissions for managing s3 bucket policies and lifecycle configurations
atlassian-labs/aws-resources pull request #16
Opened 2023-10-26 06:39 UTC by MatthewCochrane

The code in [this PR](https://github.com/atlassian/aws-infrastructure/pull/166#issuecomment-1771899236) into aws-infrastructure which adds parameters to DataCenterFormula to store avatar and/or attachment data in an S3 bucket (instead of the shared home) requires that the `JPT-dev` role gets these extra permissions to allow attaching a policy to a bucket and to create a lifecycle rule to automatically clean the bucket contents.

2023-10-26 15:35 UTC, mgrzaslewicz requested changes
Could you amend commit message and explain why it's needed?
In other words follow
https://cbea.ms/git-commit/#why-not-how

and move add the explanation from PR to commit itself - as it's something easily accessible in the code, while PR will get lost

2023-10-26 21:11 UTC, MatthewCochrane commented
> Could you amend commit message and explain why it's needed? In other words follow https://cbea.ms/git-commit/#why-not-how
> 
> and move add the explanation from PR to commit itself - as it's something easily accessible in the code, while PR will get lost

Sure thing. Updated!

2023-10-27 11:57 UTC, mgrzaslewicz approved these changes

2023-10-27 11:57 UTC, merged

2024-04-19 14:47 UTC, dagguh commented
> These permissions are required when setting the jiraSharedStorageConfig option in DataCenterFormula (in aws-infrastructure)

Then this change should have happened in [aws-infrastructure](https://github.com/atlassian/aws-infrastructure). Keep it local